sudo: required

services:
  - docker

language: java
install: true
before_install:
 - chmod +x gradlew
script:
  - ./gradlew test

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh
